# Generated by Django 5.2.8 on 2025-11-14 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AirQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('co', models.FloatField()),
                ('no2', models.FloatField()),
                ('o3', models.FloatField()),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('risk_label', models.CharField(blank=True, max_length=50, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.airqualitystation')),
            ],
        ),
    ]
