# Generated by Django 5.2.8 on 2025-11-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airqualityrecord',
            old_name='aqi',
            new_name='co_norm',
        ),
        migrations.RenameField(
            model_name='airqualitystation',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='airqualitystation',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RemoveField(
            model_name='airqualityrecord',
            name='risk_label',
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='no2_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='o3_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='pm10_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='pm25_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='air.airqualitystation'),
        ),
        migrations.AlterField(
            model_name='airqualitystation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
