# Generated by Django 5.2.8 on 2025-11-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_rename_aqi_airqualityrecord_co_norm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airqualityrecord',
            old_name='co_norm',
            new_name='aqi',
        ),
        migrations.RenameField(
            model_name='airqualitystation',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='airqualitystation',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='airqualityrecord',
            name='no2_norm',
        ),
        migrations.RemoveField(
            model_name='airqualityrecord',
            name='o3_norm',
        ),
        migrations.RemoveField(
            model_name='airqualityrecord',
            name='pm10_norm',
        ),
        migrations.RemoveField(
            model_name='airqualityrecord',
            name='pm25_norm',
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='risk_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.airqualitystation'),
        ),
        migrations.AlterField(
            model_name='airqualitystation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
