# Generated by Django 5.2.8 on 2025-11-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0003_rename_co_norm_airqualityrecord_aqi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airqualityrecord',
            name='aqi',
        ),
        migrations.RemoveField(
            model_name='airqualityrecord',
            name='risk_label',
        ),
    ]
