# Generated by Django 5.2.8 on 2025-11-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterqualitystation',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='waterqualitystation',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RemoveField(
            model_name='waterqualityrecord',
            name='risk_label',
        ),
        migrations.AddField(
            model_name='waterqualityrecord',
            name='conductivity_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualityrecord',
            name='nitrates_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualityrecord',
            name='ph_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualityrecord',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='water.waterqualitystation'),
        ),
        migrations.AlterField(
            model_name='waterqualitystation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
