# Generated by Django 5.2.8 on 2025-11-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_rename_lat_waterqualitystation_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterqualityrecord',
            name='risk_label',
        ),
    ]
