# Generated by Django 5.0 on 2024-12-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitystation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualitystation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
