# Generated by Django 5.2.8 on 2025-11-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiationrecord',
            old_name='risk_fuzzy',
            new_name='alpha_norm',
        ),
        migrations.RenameField(
            model_name='radiationstation',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='radiationstation',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RemoveField(
            model_name='radiationrecord',
            name='risk_label',
        ),
        migrations.AddField(
            model_name='radiationrecord',
            name='ambient_dose_rate_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiationrecord',
            name='beta_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiationrecord',
            name='gamma_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiationrecord',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='radiation.radiationstation'),
        ),
        migrations.AlterField(
            model_name='radiationstation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
