# Generated by Django 5.2.8 on 2025-11-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiation', '0002_rename_risk_fuzzy_radiationrecord_alpha_norm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiationrecord',
            old_name='alpha_norm',
            new_name='risk_fuzzy',
        ),
        migrations.RenameField(
            model_name='radiationstation',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='radiationstation',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='radiationrecord',
            name='ambient_dose_rate_norm',
        ),
        migrations.RemoveField(
            model_name='radiationrecord',
            name='beta_norm',
        ),
        migrations.RemoveField(
            model_name='radiationrecord',
            name='gamma_norm',
        ),
        migrations.AddField(
            model_name='radiationrecord',
            name='risk_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='radiationrecord',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiation.radiationstation'),
        ),
        migrations.AlterField(
            model_name='radiationstation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
