# Generated by Django 5.2.8 on 2025-11-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiation', '0003_rename_alpha_norm_radiationrecord_risk_fuzzy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiationrecord',
            name='risk_fuzzy',
        ),
        migrations.RemoveField(
            model_name='radiationrecord',
            name='risk_label',
        ),
    ]
