# Generated by Django 5.2.2 on 2025-11-11 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilQualityStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('heavy_metals', models.FloatField()),
                ('pesticides', models.FloatField()),
                ('moisture', models.FloatField()),
                ('fertility_index', models.FloatField(blank=True, null=True)),
                ('risk_label', models.CharField(blank=True, max_length=50, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soil.soilqualitystation')),
            ],
        ),
    ]
