# Generated by Django 5.2.8 on 2025-11-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0002_rename_latitude_soilqualitystation_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilqualitystation',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='soilqualitystation',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='soilqualityrecord',
            name='heavy_metals_norm',
        ),
        migrations.RemoveField(
            model_name='soilqualityrecord',
            name='pesticides_norm',
        ),
        migrations.RemoveField(
            model_name='soilqualityrecord',
            name='ph_norm',
        ),
        migrations.AddField(
            model_name='soilqualityrecord',
            name='risk_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='soilqualityrecord',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soil.soilqualitystation'),
        ),
        migrations.AlterField(
            model_name='soilqualitystation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
