# Generated by Django 5.2.8 on 2025-11-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0003_rename_lat_soilqualitystation_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilqualityrecord',
            name='risk_label',
        ),
    ]
